// Maps a category's theme color name to the concrete Tailwind classes used
// across cards, headers and tags. Centralising this means every usage site
// stays a lookup rather than a hand-built template string, and only this
// file (plus tailwind.config.js's safelist) needs updating to add a color.
const THEMES = {
  indigo: {
    bg50: 'bg-indigo-50',
    solid: 'bg-indigo-600',
    solidHover: 'hover:bg-indigo-700',
    gradient: 'from-indigo-500 to-indigo-700',
    text: 'text-indigo-700',
    border: 'border-indigo-200',
    ring: 'ring-indigo-500',
  },
  teal: {
    bg50: 'bg-teal-50',
    solid: 'bg-teal-600',
    solidHover: 'hover:bg-teal-700',
    gradient: 'from-teal-500 to-teal-700',
    text: 'text-teal-700',
    border: 'border-teal-200',
    ring: 'ring-teal-500',
  },
  sky: {
    bg50: 'bg-sky-50',
    solid: 'bg-sky-600',
    solidHover: 'hover:bg-sky-700',
    gradient: 'from-sky-500 to-sky-700',
    text: 'text-sky-700',
    border: 'border-sky-200',
    ring: 'ring-sky-500',
  },
  amber: {
    bg50: 'bg-amber-50',
    solid: 'bg-amber-600',
    solidHover: 'hover:bg-amber-700',
    gradient: 'from-amber-500 to-amber-700',
    text: 'text-amber-700',
    border: 'border-amber-200',
    ring: 'ring-amber-500',
  },
  emerald: {
    bg50: 'bg-emerald-50',
    solid: 'bg-emerald-600',
    solidHover: 'hover:bg-emerald-700',
    gradient: 'from-emerald-500 to-emerald-700',
    text: 'text-emerald-700',
    border: 'border-emerald-200',
    ring: 'ring-emerald-500',
  },
  cyan: {
    bg50: 'bg-cyan-50',
    solid: 'bg-cyan-600',
    solidHover: 'hover:bg-cyan-700',
    gradient: 'from-cyan-500 to-cyan-700',
    text: 'text-cyan-700',
    border: 'border-cyan-200',
    ring: 'ring-cyan-500',
  },
  violet: {
    bg50: 'bg-violet-50',
    solid: 'bg-violet-600',
    solidHover: 'hover:bg-violet-700',
    gradient: 'from-violet-500 to-violet-700',
    text: 'text-violet-700',
    border: 'border-violet-200',
    ring: 'ring-violet-500',
  },
  orange: {
    bg50: 'bg-orange-50',
    solid: 'bg-orange-600',
    solidHover: 'hover:bg-orange-700',
    gradient: 'from-orange-500 to-orange-700',
    text: 'text-orange-700',
    border: 'border-orange-200',
    ring: 'ring-orange-500',
  },
  rose: {
    bg50: 'bg-rose-50',
    solid: 'bg-rose-600',
    solidHover: 'hover:bg-rose-700',
    gradient: 'from-rose-500 to-rose-700',
    text: 'text-rose-700',
    border: 'border-rose-200',
    ring: 'ring-rose-500',
  },
  blue: {
    bg50: 'bg-blue-50',
    solid: 'bg-blue-600',
    solidHover: 'hover:bg-blue-700',
    gradient: 'from-blue-500 to-blue-700',
    text: 'text-blue-700',
    border: 'border-blue-200',
    ring: 'ring-blue-500',
  },
  lime: {
    bg50: 'bg-lime-50',
    solid: 'bg-lime-600',
    solidHover: 'hover:bg-lime-700',
    gradient: 'from-lime-500 to-lime-700',
    text: 'text-lime-800',
    border: 'border-lime-200',
    ring: 'ring-lime-500',
  },
  fuchsia: {
    bg50: 'bg-fuchsia-50',
    solid: 'bg-fuchsia-600',
    solidHover: 'hover:bg-fuchsia-700',
    gradient: 'from-fuchsia-500 to-fuchsia-700',
    text: 'text-fuchsia-700',
    border: 'border-fuchsia-200',
    ring: 'ring-fuchsia-500',
  },
  red: {
    bg50: 'bg-red-50',
    solid: 'bg-red-600',
    solidHover: 'hover:bg-red-700',
    gradient: 'from-red-500 to-red-700',
    text: 'text-red-700',
    border: 'border-red-200',
    ring: 'ring-red-500',
  },
  yellow: {
    bg50: 'bg-yellow-50',
    solid: 'bg-yellow-600',
    solidHover: 'hover:bg-yellow-700',
    gradient: 'from-yellow-500 to-yellow-700',
    text: 'text-yellow-800',
    border: 'border-yellow-200',
    ring: 'ring-yellow-500',
  },
  green: {
    bg50: 'bg-green-50',
    solid: 'bg-green-600',
    solidHover: 'hover:bg-green-700',
    gradient: 'from-green-500 to-green-700',
    text: 'text-green-700',
    border: 'border-green-200',
    ring: 'ring-green-500',
  },
  purple: {
    bg50: 'bg-purple-50',
    solid: 'bg-purple-600',
    solidHover: 'hover:bg-purple-700',
    gradient: 'from-purple-500 to-purple-700',
    text: 'text-purple-700',
    border: 'border-purple-200',
    ring: 'ring-purple-500',
  },
  pink: {
    bg50: 'bg-pink-50',
    solid: 'bg-pink-600',
    solidHover: 'hover:bg-pink-700',
    gradient: 'from-pink-500 to-pink-700',
    text: 'text-pink-700',
    border: 'border-pink-200',
    ring: 'ring-pink-500',
  },
  stone: {
    bg50: 'bg-stone-50',
    solid: 'bg-stone-600',
    solidHover: 'hover:bg-stone-700',
    gradient: 'from-stone-500 to-stone-700',
    text: 'text-stone-700',
    border: 'border-stone-200',
    ring: 'ring-stone-500',
  },
  gray: {
    bg50: 'bg-gray-50',
    solid: 'bg-gray-600',
    solidHover: 'hover:bg-gray-700',
    gradient: 'from-gray-500 to-gray-700',
    text: 'text-gray-700',
    border: 'border-gray-200',
    ring: 'ring-gray-500',
  },
  slate: {
    bg50: 'bg-slate-50',
    solid: 'bg-slate-600',
    solidHover: 'hover:bg-slate-700',
    gradient: 'from-slate-500 to-slate-700',
    text: 'text-slate-700',
    border: 'border-slate-200',
    ring: 'ring-slate-500',
  },
}

export function getTheme(color) {
  return THEMES[color] ?? THEMES.indigo
}
